import { z } from "zod";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
} from "docx";
import { Client } from "@microsoft/microsoft-graph-client";
import "isomorphic-fetch";

export const CompileResponseInput = z.object({
  rfpTitle: z.string().describe("Title of the RFP (used as document title)"),
  answers: z
    .array(
      z.object({
        questionId: z.string(),
        section: z.string(),
        question: z.string(),
        answer: z.string(),
        citations: z.array(z.object({ title: z.string(), url: z.string(), excerpt: z.string() })),
        confidence: z.number(),
        needsReview: z.boolean(),
      })
    )
    .describe("Array of drafted answers to include"),
  sharePointSiteId: z.string().describe("SharePoint site ID to upload to"),
  accessToken: z.string().describe("Graph access token (Files.ReadWrite.All, Sites.ReadWrite.All)"),
});

export type AnswerItem = z.infer<typeof CompileResponseInput>["answers"][number];

export type CompileResult = {
  sharePointUrl: string;
  itemId: string;
  fileName: string;
  totalAnswers: number;
  needsReviewCount: number;
};

export async function compileResponse(
  rfpTitle: string,
  answers: AnswerItem[],
  sharePointSiteId: string,
  accessToken: string
): Promise<CompileResult> {
  // Group answers by section
  const sections = new Map<string, typeof answers>();
  for (const a of answers) {
    if (!sections.has(a.section)) sections.set(a.section, []);
    sections.get(a.section)!.push(a);
  }

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      text: `RFP Response: ${rfpTitle}`,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      text: `Generated by RFPRespond • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({ text: "" }),
  ];

  for (const [sectionName, sectionAnswers] of sections) {
    children.push(
      new Paragraph({ text: sectionName, heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: "" })
    );

    for (const a of sectionAnswers) {
      const needsReviewBadge = a.needsReview ? " ⚠ NEEDS SME REVIEW" : "";
      children.push(
        new Paragraph({
          text: `${a.questionId}${needsReviewBadge}`,
          heading: HeadingLevel.HEADING_2,
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Q: ", bold: true }),
            new TextRun({ text: a.question }),
          ],
        }),
        new Paragraph({ text: "" }),
        new Paragraph({
          children: [
            new TextRun({ text: "A: ", bold: true }),
            new TextRun({ text: a.answer }),
          ],
        }),
        new Paragraph({ text: "" })
      );

      if (a.citations.length > 0) {
        children.push(
          new Paragraph({ children: [new TextRun({ text: "Sources:", italics: true, bold: true })] })
        );
        for (const c of a.citations) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: `• ${c.title}` }),
              ],
              indent: { left: 360 },
            })
          );
        }
        children.push(new Paragraph({ text: "" }));
      }
    }
  }

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);

  const sanitized = rfpTitle.replace(/[^a-zA-Z0-9\s-]/g, "").replace(/\s+/g, "_");
  const fileName = `RFP_Response_${sanitized}_${Date.now()}.docx`;

  const graphClient = Client.init({ authProvider: (done) => done(null, accessToken) });

  const uploadResponse = await graphClient
    .api(`/sites/${sharePointSiteId}/drive/root:/RFPCorpus/Responses/${fileName}:/content`)
    .put(buffer);

  return {
    sharePointUrl: uploadResponse.webUrl,
    itemId: uploadResponse.id,
    fileName,
    totalAnswers: answers.length,
    needsReviewCount: answers.filter((a: AnswerItem) => a.needsReview).length,
  };
}
